import MetodologiaSlider from "./MetodologiaSlider";

const metodologias = [
  {
    titulo: "Bioquímica clínica e inmunoensayos (análisis hormonales, serológicos y antigénicos)",
    texto: [
      "Disponemos de instrumentación Atellica Solution de Siemens para todos los análisis de bioquímica clínica. Los inmunoensayos se realizan utilizando tres metodologías diferentes:",
      "• Quimioluminiscencia en los instrumentos Atellica Solution e Inmulite 2000 XPi de Siemens, y en plataformas Maglumi X3 de Snibe.",
      "• Electroquimioluminiscencia en los instrumentos Cobas e 411 de Roche.",
      "• ELFA (Enzimoinmunoensayo ligado a fluorescencia) en el mini VIDAS de BioMérieux.",
      "También disponemos de un sistema de gases en sangre RAPIDLab 348 EX de Siemens que, además de gases en sangre, permite cuantificar el Calcio iónico.",
      "Todas estas tecnologías nos permiten ofrecer un amplio catálogo de prestaciones según los requerimientos médicos y de pacientes.",
      "Análisis disponibles",
      "Bioquímica clínica:",
      "• Acetona",
      "• Ácidos Biliares",
      "• Ácido láctico",
      "• Ácido úrico",
      "• Albúmina",
      "• µ-albuminuria",
      "• Amilasa",
      "• Amonio",
      "• Bicarbonato",
      "• Bilirrubina total y directa",
      "• Calcio",
      "• Calcio iónico",
      "• Colesterol",
      "• Colinesterasa",
      "• Creatinina",
      "• Creatinina + Velocidad Filtrado Glomerular (VFG)",
      "• Clearence de Creatinina",
      "• C.K. Total",
      "• C.K. fracción MB",
      "• Electrolitos plasmáticos (Na-K-Cl)",
      "• Ferremia + TIBC",
      "• Fosfatasa alcalina",
      "• Fósforo",
      "• Gama Glutamiltranspeptidasa",
      "• Gases arteriales",
      "• Gases venosos",
      "• Glicemia",
      "• Homocisteína plasmática",
      "• L.D.H. (Deshidrogenasa Láctica)",
      "• Lipasa",
      "• Litio",
      "• Magnesio",
      "• Péptido Natriurético Cerebral (NT-proBNP)",
      "• Perfil Bioquímico",
      "• Perfil Hepático",
      "• Perfil Lipídico",
      "• Proteínas totales",
      "• Proteinuria",
      "• Transaminasas (GOT/GPT)",
      "• Uremia",
      "Análisis hormonales:",
      "• Adenocorticotrofina (ACTH)",
      "• Aldosterona",
      "• Androstenediona",
      "• Anti Mülleriana",
      "• Cortisol",
      "• Cortisol Libre Urinario",
      "• Cortisol Libre Salival Nocturno",
      "• D.H.E.A – Sulfato",
      "• Eritropoyetina",
      "• Estradiol",
      "• FSH",
      "• LH",
      "• Gastrina",
      "• HCG (Fracción β)",
      "• HGH (Crecimiento)",
      "• Índice androgénico",
      "• Insulina",
      "• IGF-1",
      "• IGFBP-3",
      "• Parathormona (PTH intacta)",
      "• 17-OH-Progesterona",
      "• Péptido-C",
      "• Prolactina",
      "• Prolactina (Macro o Big-Big)",
      "• Progesterona",
      "• Renina Directa Cuantitativa",
      "• S.H.B.G",
      "• Testosterona total",
      "• Testosterona libre",
      "• T3",
      "• T3 Libre",
      "• T4",
      "• T4 Libre",
      "• TSH",
      "• Tiroglobulina",
      "• Anticuerpos Antitiroídeos (TPO + TG)",
      "• TRAb, Anticuerpos Anti Receptor de TSH",
      "Análisis antigénicos:",
      "• Ácido Fólico",
      "• Folato eritrocitario",
      "• β-2-Microglobulina",
      "• Ca 125",
      "• Ca 19-9",
      "• Ca 15-3",
      "• Calcitonina",
      "• CEA",
      "• Ferritina",
      "• α-Fetoproteína",
      "• Gonadotrofina Coriónica Fracción β",
      "• Procalcitonina",
      "• PSA Total",
      "• PSA Total y Libre",
      "• Tiroglobulina",
      "• Vitamina B-12",
      "• Vitamina D total",
      "Análisis serológicos:",
      "• Anticuerpos anti-Treponémicos",
      "• Anti-SARS-CoV-2 IgG/IgM",
      "• Bartonella Henselae IgG/IgM",
      "• Chagas IgG",
      "• Chlamydias Trachomatis IgG/IgM",
      "• Citomegalovirus IgG/IgM",
      "• Epstein-Barr IgG/IgM",
      "• Hepatitis A (IgM)",
      "• Hepatitis B (Ag. de Superficie)",
      "• Hepatitis B, Anticore Total (Anti HBc Total)",
      "• Hepatitis B, Anticore IgM (Anti HBc IgM)",
      "• Hepatitis B, Anti Antígeno de Superficie (Anti HBs)",
      "• Hepatitis C (Anticuerpo IgG)",
      "• Herpes I IgG/IgM",
      "• Herpes II IgG/IgM",
      "• HTLV 1 y 2",
      "• Mycoplasma Pneumoniae IgG/IgM",
      "• Rubéola IgG/IgM",
      "• Toxoplasmosis IgG/IgM",
    ],
    imagenes: [
      { src: "/metodologias/atellica-solution.jpeg", nombre: "Siemens Atellica Solution" },
      { src: "/metodologias/immulite-2000-xpi.jpeg", nombre: "Siemens Immulite 2000 XPi" },
      { src: "/metodologias/cobas-e-411.png", nombre: "Roche Cobas e 411" },
      { src: "/metodologias/mini-vidas.png", nombre: "BioMérieux Mini VIDAS" },
      { src: "/metodologias/rapidlab-348ex.png", nombre: "Siemens RAPIDLab 348EX" },
      { src: "/metodologias/maglumi-x3.png", nombre: "Snibe Maglumi X3" },
    ],
  },
  {
    titulo: "Pruebas de Hemostasia (Coagulación)",
    texto: [
      "Analizadores de coagulación CS-2500 Sysmex completamente automatizados que, a través de métodos Coagulativo, Cromogénico, Inmunológico y de agregación, permiten un amplio menú de análisis:",
      "• Tiempo de Protrombina (seg, %, INR)",
      "• Tiempo parcial de tromboplastina (TTPK)",
      "• Fibrinógeno",
      "• Dímero-D",
      "• Antitrombina III",
      "• Anticoagulante Lúpico",
      "• Factor von Willebrand",
      "• Cofactor de Ristocetina",
      "• Factor VII coagulante",
      "• Factor VIII coagulante",
      "• Proteína C",
      "• Proteína S",
      "• Proteína S Libre",
      "• Resistencia a la Proteína C Activada",
    ],
    imagenes: [{ src: "/metodologias/sysmex-cs2500.jpeg", nombre: "CS-2500 Sysmex" }],
  },
  {
    titulo: "Analizadores de hematología y VHS automatizados. XN-1000 Sysmex y Autocompact Starrsed RS de Mechatronics.",
    texto: [
      "Los analizadores XN-1000 de Sysmex, mediante técnica de citometría de flujo de fluorescencia, procesan hasta 100 muestras por hora de sangre completa, ofreciendo una amplia gama de parámetros que añaden valor clínico al recuento sanguíneo:",
      "• Recuento preciso y confiable de leucocitos totales",
      "• Eritroblastos reportados automáticamente en todos los recuentos sanguíneos",
      "• Diferencial de leucocitos de 6 partes",
      "• Análisis de la cantidad y calidad celular de la serie eritrocitaria",
      "• Recuento de reticulocitos",
      "• Análisis plaquetario adicional por citometría de flujo fluorescente",
      "Por su parte, los Autocompact Starrsed RS de Mechatronics permiten la medición automatizada de hasta 100 velocidades de eritrosedimentación por hora (VHS) — parámetro muy importante del hemograma — con una metodología comparable al gold estándar o de referencia, el método de Westergren.",
    ],
    imagenes: [
      { src: "/metodologias/sysmex-xn1000.png", nombre: "XN-1000 Sysmex" },
      { src: "/metodologias/autocompact-starrsed-rs.jpeg", nombre: "Autocompact Starrsed RS" },
    ],
  },
  {
    titulo: "Laboratorio de microbiología.",
    texto: [
      "El VITEK 2 Compact responde a los desafíos globales en atención sanitaria, como la aparición de microorganismos multirresistentes, ofreciendo a los laboratorios de microbiología una herramienta flexible y precisa. Este equipo permite mejorar el éxito terapéutico y los resultados clínicos mediante una identificación microbiana confiable y un análisis automatizado de susceptibilidad antibiótica. Además, reduce significativamente los tiempos de entrega de resultados, que no superan las 5 a 8 horas, gracias a su metodología completamente automatizada y la validación/transferencia automática de datos.",
      "Análisis disponibles:",
      "• Identificación de levaduras",
      "• Identificación de bacterias gram-negativos",
      "• Identificación de bacterias gram-positivos",
      "• Pruebas de sensibilidad",
    ],
    imagenes: [{ src: "/metodologias/vitek-2-compact.jpeg", nombre: "VITEK 2 Compact" }],
  },
  {
    titulo: "Sistema automatizado de uroanálisis",
    texto: [
      "El Atellica 1500 de Siemens combina el analizador de química urinaria CLINITEK Novus con el avanzado analizador de sedimento urinario Atellica UAS 800, ofreciendo una solución completamente digital. Este sistema establece un nuevo estándar en precisión y eficiencia, permitiendo procesar hasta 240 muestras por hora con menor intervención del personal y en menos tiempo, manteniendo consistentemente resultados de alta calidad.",
      "Exámenes:",
      "• Química urinaria",
      "• Sedimento urinario autónomo",
      "• Orina completa con sedimento",
    ],
    imagenes: [{ src: "/metodologias/atellica-1500.jpeg", nombre: "Siemens Atellica 1500" }],
  },
  {
    titulo: "Estudios de autoinmunidad (EliA, Fluoroenzimoinmunoensayo) y detección de IgE específicas (ImmunoCAP).",
    texto: [
      "EliA en los instrumentos Phadia 250 de Thermo Fisher Scientific permite analizar cuantitativamente la presencia en muestras de pacientes de más de 50 autoanticuerpos marcadores de enfermedades autoinmunes, con altos niveles de sensibilidad y especificidad.",
      "Disponemos de los siguientes análisis a través de esta tecnología:",
      "• Anti DNA",
      "• Anti Ena",
      "• Anti Ro",
      "• Anti La",
      "• Anti Sm",
      "• Anti RNP",
      "• Anti Scl70",
      "• Anti Jo-1",
      "• Anti Proteinasa 3 (PR3)",
      "• Anti Mieloperoxidasa (MPO)",
      "• Anti Membrana Basal Glomerular",
      "• Anti Saccharomyces Cerevisiae (ASCA), IgG e IgA",
      "• Anti Transglutaminasa IgA",
      "• Anti Péptidos Deaminados de Gliadina, IgG e IgA",
      "• Anti Cardiolipinas, IgG e IgM",
      "• Anti β-2 Glicoproteínas, IgG e IgM",
      "• Anti Péptido Citrulinado Cíclico (CCP3)",
      "• Anti Ribosoma P (Rib-P)",
      "• Anti DFS70",
      "ImmunoCAP es el estándar de oro (Gold Standard o método de referencia) para el diagnóstico in vitro de alergias, a través de la medición de IgE específicas en sangre.",
      "Disponemos de un amplio menú de alérgenos para la medición de IgE específicas:",
      "Alérgenos alimentarios:",
      "• Almeja",
      "• Almendras",
      "• Arroz",
      "• Atún",
      "• Avena",
      "• Camarones",
      "• Carne de cerdo",
      "• Carne de pavo",
      "• Carne de pollo",
      "• Carne de vacuno",
      "• Caseína",
      "• Chocolate",
      "• Choritos",
      "• Clara de huevo",
      "• Frutilla",
      "• Garbanzo",
      "• Gluten",
      "• Jaiba",
      "• α-Lactalbúmina",
      "• β-Lactoglobulina",
      "• Leche de vaca",
      "• Lenteja",
      "• Maíz",
      "• Maní",
      "• Manzana",
      "• Naranja",
      "• Nueces",
      "• Palta",
      "• Piña",
      "• Plátano",
      "• Salmón",
      "• Sésamo",
      "• Soya",
      "• Tomate",
      "• Trigo",
      "• Yema de huevo",
      "Mezclas alimentarias:",
      "• Mezcla de cereales (Trigo/ Avena/ Maíz/ Sésamo/ Alforfón o Trigo sarraceno)",
      "• Mezcla de crustáceos, moluscos, peces (Bacalao/ Camarones/ Mejillón/ Atún/ Salmón)",
      "• Mezcla de frutos secos (Maní/ Avellana/ Nuez de Brasil/ Almendra/ Coco)",
      "Alérgenos inhalatorios — Árboles:",
      "• Arce",
      "• Ciprés",
      "• Fresno",
      "• Plátano oriental",
      "• Mezcla 1 árboles (Arce/ Abedul/ Roble/ Olmo/ Nogal)",
      "• Mezcla 2 árboles (Roble/ Olmo/ Plátano oriental/ Sauce/ Álamo)",
      "• Mezcla 3 árboles (Olivo/ Sauce/ Pino/ Eucaliptus/ Acacia/ Melaleuca Cayeput)",
      "Gramíneas:",
      "• Grama Bermuda (Cynodon Dactylon o Chépica)",
      "• Grama Timotea (Phleum pratense)",
      "• Mezcla Pasto/Gramínea (Pasto Ovillo/ Festuca/ Ballica/ Hierba Timotea/ Pasto Mallín)",
      "Malezas:",
      "• Plántago lanceolata o Llantén",
      "• Rumex Acetosella o Acedera",
      "• Parietaria Judaica",
      "• Mezcla de malezas (Ambrosia/ Llantén o Plántago/ Artemisia/ Bledo/ Salsola)",
      "Mohos y levaduras:",
      "• Alternaria alternata",
      "• Aspergillus Fumigatus",
      "• Candida Albicans",
      "• Mezcla de hongos (Penicillium/ Cladosporium/ Aspergillus/ Alternaria)",
      "Alérgenos proteínas animales, ácaros, polvo de casa:",
      "• Epitelio de gato",
      "• Epitelio de perro",
      "• Plumas de ganso",
      "• Cucaracha germánica",
      "• Cucaracha americana",
      "• Dermatofagoides Pteronyssinus",
      "• Dermatofagoides Farinae",
      "• Polvo de casa H1",
      "• Polvo de casa H2",
      "Alérgenos de contacto:",
      "• Látex",
    ],
    imagenes: [{ src: "/metodologias/phadia-250.jpeg", nombre: "Phadia 250 Thermo Fisher Scientific" }],
  },
  {
    titulo: "Electroforesis en gel de agarosa",
    texto: [
      "Disponemos de un instrumento Sebia Hydrasys, para la automatización del análisis electroforético.",
      "La electroforesis en gel se utiliza en los laboratorios clínicos para detectar proteínas anómalas en suero, orina y otros fluidos biológicos, así como para diagnosticar distintas anomalías que cursan con cambios atípicos en diferentes patrones proteicos.",
      "La electroforesis e inmunofijación de inmunoglobulinas en sangre y orina en gel de agarosa con tinción negro amido, se considera el método de referencia para estos análisis.",
      "Análisis disponibles:",
      "• Electroforesis de proteínas séricas",
      "• Electroforesis de proteínas urinarias",
      "• Electroforesis de hemoglobinas",
      "• Inmunofijación de inmunoglobulinas séricas (Mielomas, Enfermedad de Bence Jones, Macroglobulinemia de Waldenström, Enfermedad de Cadenas pesadas de inmunoglobulinas)",
      "• Inmunofijación de inmunoglobulinas urinarias (IF, Proteinuria de Bence Jones)",
    ],
    imagenes: [{ src: "/metodologias/sebia-hydrasys.png", nombre: "Sebia Hydrasys" }],
  },
  {
    titulo: "Autoinmunidad. Inmunofluorescencia indirecta (IFI)",
    texto: [
      "Disponemos de instrumentos completamente automatizados para el procesamiento de pruebas de inmunofluorescencia indirecta (IFI), entre ellos los sistemas Helios e IFI UNIQO 160. El sistema Helios incorpora microscopía de fluorescencia con tecnología LED de alta resolución.",
      "Estos equipos permiten la identificación de las muestras mediante lectura de código de barras y la ejecución automatizada de los ensayos programados, abarcando desde la dilución inicial de la muestra hasta la adquisición y análisis de imágenes para la interpretación de los patrones de inmunofluorescencia.",
      "Tests disponibles:",
      "• Anticuerpos anti nucleares (ANA)",
      "• Anticuerpos anti DNA",
      "• Anticuerpos anti mitocondriales (AMA)",
      "• Anticuerpos anti músculo liso (ASMA)",
      "• Anticuerpos anti células parietales gástricas",
      "• Anticuerpos anti LKM-1",
      "• Anticuerpos anti Endomisio",
      "• Anticuerpos anti Citoplasma de Neutrófilos (P y C ANCA)",
      "• Anticuerpos anti Treponémicos (FTA-ABS)",
    ],
    imagenes: [
      { src: "/metodologias/aesku-helios.png", nombre: "Aesku Helios" },
      { src: "/metodologias/ifi-uniqo-160.png", nombre: "IFI UNIQO 160" },
    ],
  },
  {
    titulo: "Nefelometría",
    texto: [
      "Los sistemas Atellica NEPH 630 de Siemens son instrumentos de alta sofisticación que, a través de la metodología considerada el método de referencia o 'gold standard' para el análisis cuantitativo de proteínas plasmáticas de interés clínico, son capaces de medir más de 70 analitos distintos a velocidades de hasta 65 test/Hora. Nuestro laboratorio dispone de 2 de estos instrumentos, suficientes para cubrir los requerimientos de este tipo de exámenes.",
      "Análisis disponibles:",
      "• Proteína C Reactiva",
      "• Proteína C Reactiva ultra sensible",
      "• Complemento C3",
      "• Complemento C4",
      "• Inmunoglobulina IgG",
      "• Inmunoglobulina IgA",
      "• Inmunoglobulina IgM",
      "• Inmunoglobulina IgA secretora",
      "• Inmunoglobulina IgE",
      "• Factor Reumatoide",
      "• Antiestrepolisina O",
      "• β-2 Microglobulina",
      "• Lipoproteína (a)",
      "• Homocisteína",
      "• Transferrina",
      "• Haptoglobina",
    ],
    imagenes: [{ src: "/metodologias/atellica-neph-630.png", nombre: "Atellica NEPH 630 de Siemens" }],
  },
  {
    titulo: "Inmunoblot: EUROBlotOne Euroimmun",
    texto: [
      "El inmunoblot es una técnica relativamente nueva que permite detectar una gran variedad de autoanticuerpos patológicos en muestras de pacientes, específicos de distintas enfermedades autoinmunes. El tratamiento de las pruebas es totalmente automatizado en el EUROBlotOne de Euroimmun, instrumento que permite realizar simultáneamente hasta 44 inmunoblots.",
      "Análisis disponibles:",
      "• Perfil Ana (IgG), 23 antígenos",
      "• Perfil Miopatías inflamatorias, 16 antígenos",
      "• Perfil enfermedades hepáticas, 10 antígenos",
      "• Perfil Esclerosis sistémicas, 13 antígenos",
      "• Perfil de antígenos citoplasmáticos de HEp-2, 10 antígenos",
      "• Perfil enfermedades gastrointestinal IgG, 5 antígenos",
      "• Perfil enfermedades gastrointestinales IgA, 3 antígenos",
      "• Anticuerpos anti DFS70 (Patrón Nuclear Granular Fino Denso)",
    ],
    imagenes: [{ src: "/metodologias/euroblotone.jpeg", nombre: "Euroimmun EUROBlotOne" }],
  },
  {
    titulo: "Citometría de Flujo",
    texto: [
      "Disponemos de un citómetro de flujo Becton Dickinson FACSVia que permite el estudio y cuantificación de subpoblaciones linfocitarias.",
      "Análisis disponibles:",
      "• Cuantificación de subpoblaciones linfocitarias B, T y Natural Killer",
      "• Cuantificación de linfocitos CD3, CD4, CD8 y CD45",
    ],
    imagenes: [{ src: "/metodologias/facsvia.png", nombre: "Becton Dickinson FACSVia" }],
  },
  {
    titulo: "Analizador ELISA",
    texto: [
      "El Instrumento Elisys Uno de Human permite programar automáticamente cualquier ensayo ELISA, con muy buenos niveles de exactitud y reproducibilidad, capaz de procesar hasta 80 muestras simultáneamente, con cálculo, validación y transmisión automática de resultados.",
      "Test realizados con este instrumento:",
      "• Calprotectina fecal",
      "• Elastasa-1 Pancreática fecal",
      "• Helicobacter Pylori Antígeno en deposición",
      "• Anti Receptor de Fosfolipasa A2 (Anti PLA2R) en sangre",
      "• Anticuerpos Anti-HMGCR (3-Hidroxi-3-Metilglutaril-Coenzima A Reductasa) (HMG-CoA)",
    ],
    imagenes: [{ src: "/metodologias/elisys-uno.png", nombre: "Human Elisys Uno" }],
  },
  {
    titulo: "Diagnóstico Molecular",
    texto: [
      "Reacción en cadena de la polimerasa a tiempo real",
      "La reacción en cadena de la polimerasa (PCR) es una técnica de biología molecular que permite la rápida replicación del ADN. Con la PCR, cantidades mínimas de material genético pueden ser amplificadas millones de veces en pocas horas, permitiendo la detección rápida y fiable de los marcadores genéticos de enfermedades infecciosas, cáncer y desordenes genéticos.",
      "Nuestra instrumentación:",
      "• Roche cobas z 480",
      "• Roche LightCycler 2.0",
      "• Bio Rad CFX96 Real-Time System (2 instrumentos)",
      "• Extractores de ácidos nucleicos para diagnóstico clínico GenePure Pro (2 instrumentos)",
      "Análisis disponibles (Real Time PCR):",
      "• Patógenos virales respiratorios",
      "• Coronavirus, Covid-19",
      "• Patógenos bacterianos respiratorios",
      "• Patógenos virales gástricos",
      "• Patógenos bacterianos gástricos",
      "• Panel Parásitos gastrointestinales",
      "• Patógenos genitourinarios (Enfermedades de transmisión sexual)",
      "• Detección de Chlamydia Trachomatis y Neisseria Gonorrhoeae",
      "• Detección ADN de virus papiloma humano de alto riesgo e identificación de los genotipos 16, 18 y 45",
      "• Carga viral del Virus Inmunodeficiencia Humana (VIH)",
      "• Factor V Leiden (mutación G1691A)",
      "• Factor II de la protrombina (Mutación G20210A)",
      "• Tipificación HLA-B27",
      "• Estudio genético molecular de malabsorción de Lactosa",
    ],
    imagenes: [
      { src: "/metodologias/cobas-z480.jpeg", nombre: "Roche cobas z 480" },
      { src: "/metodologias/lightcycler-2.jpeg", nombre: "Roche LightCycler 2.0" },
      { src: "/metodologias/cfx96-real-time.png", nombre: "Bio Rad CFX96 Real-Time System" },
      { src: "/metodologias/genepure-pro.jpeg", nombre: "GenePure Pro" },
    ],
  },
  {
    titulo: "Cromatografía Líquida de Alta Resolución",
    texto: [
      "La cromatografía líquida de alta resolución (HPLC) es considerado el método de referencia para la medición de diversos analitos de interés clínico, entre otros la Hemoglobina Glicosilada y los niveles plasmáticos de drogas terapéuticas.",
      "Instrumentación disponible:",
      "El cromatógrafo líquido de alta resolución D-100 de Bio-Rad es un instrumento orientado únicamente al análisis de la Hemoglobina glicada. Es una metodología certificada por el NGSP (National Glycohemoglobin Standardization Program) totalmente automática, capaz de realizar alrededor de 80 análisis por hora, con altos niveles de precisión y exactitud.",
      "El cromatógrafo líquido de alta resolución HPLC Hitachi Chromaster es la instrumentación empleada en Aclin para la medición de niveles plasmáticos de drogas terapéuticas. HPLC es el método Gold Standard de referencia para este tipo de análisis.",
      "Análisis disponibles:",
      "• Hemoglobina Glicosilada (HbA1c)",
      "• Niveles plasmáticos de anticonvulsivantes",
      "• Ácido Valpróico total y libre",
      "• Carbamazepina total",
      "• Fenitoína total y libre",
      "• Fenobarbital total y libre",
      "• Primidona total",
      "• Lamotrigina total",
      "• Levetiracetam total",
      "• Oxcarbazepina",
      "• Clonazepam",
      "• Nivel plasmático de Ácido Micofenólico",
      "• Nivel plasmático de Paracetamol",
      "• Nivel plasmático de Tacrolimus",
      "• Nivel plasmático de Teofilina",
    ],
    imagenes: [
      { src: "/metodologias/d100-biorad.png", nombre: "Bio-Rad D-100" },
      { src: "/metodologias/hplc-chromaster.jpeg", nombre: "HPLC Hitachi Chromaster" },
    ],
  },
  {
    titulo: "Inmunohematología",
    texto: [
      "El instrumento WADiana de Grifols es completamente automatizado para pruebas inmunohematológicas por técnica de aglutinación en gel. Lectura de código de barra de muestras y reactivos, procesamiento automático y validación y transmisión de resultados en línea.",
      "Test disponibles:",
      "• Grupo ABO y grupo Rh",
      "• Test de Coombs Indirecto",
      "• Prueba de Antiglobulina Directa",
    ],
    imagenes: [{ src: "/metodologias/wadiana-grifols.jpeg", nombre: "Grifols WADiana" }],
  },
];

export default function MetodologiasPage() {
  return (
    <div>
      {/* Título y descripción */}
      <div className="max-w-5xl mx-auto px-4 pt-10 pb-6">
        <h1 className="text-4xl md:text-5xl font-black text-[#087849] leading-tight mb-4">
          Metodologías<br />y equipamiento
        </h1>
        <p className="text-gray-600 text-base md:text-lg max-w-2xl">
          Aclin cuenta con equipamiento de última generación y metodologías de vanguardia para garantizar la precisión y confiabilidad en cada resultado.
        </p>
      </div>

      <div className="max-w-5xl mx-auto px-4 pb-16">
        <section>
          <div>
            {metodologias.map((m, i) => (
              <details
                key={i}
                className="group"
              >
                <summary
                  className={`flex items-center gap-3 px-5 py-4 cursor-pointer transition list-none ${
                    i % 2 === 0 ? "bg-white" : "bg-[#f0faf5]"
                  } hover:bg-[#e0f5ea]`}
                >
                  <span className="shrink-0 text-[#087849] text-base font-bold transition-transform duration-200 group-open:rotate-180">
                    ▼
                  </span>
                  <span className="font-semibold text-gray-800 text-sm md:text-base">{m.titulo}</span>
                </summary>

                <div className="px-5 py-5 bg-gray-50 border-t border-gray-200">
                  <div className="flex flex-col md:flex-row gap-6">
                    {/* Texto */}
                    {m.texto.length > 0 && (
                      <div className="flex-1 text-sm text-gray-700 space-y-2 leading-relaxed">
                        {m.texto.map((linea, j) => (
                          <p key={j}>{linea}</p>
                        ))}
                      </div>
                    )}

                    {/* Imágenes */}
                    <MetodologiaSlider imagenes={m.imagenes} />
                  </div>
                </div>
              </details>
            ))}
          </div>
        </section>
      </div>
    </div>
  );
}
